In [ ]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
dataset = pd.read_csv('milk.csv')
train_data = np.array(dataset)[:,:-1]
print(train_data)
train_label = np.array(dataset)[:,-1]
print(train_label)

[[6.6 35 1 ... 1 0 254]
 [6.6 36 0 ... 0 1 253]
 [8.5 70 1 ... 1 1 246]
 ...
 [3.0 40 1 ... 1 1 255]
 [6.8 43 1 ... 1 0 250]
 [8.6 55 0 ... 1 1 255]]
['high' 'high' 'low' ... 'low' 'high' 'low']


#Metode Min-Max

In [ ]:
from sklearn.preprocessing import MinMaxScaler

sc = MinMaxScaler(feature_range=(0, 1))
data = sc.fit_transform(train_data)
print(data)

[[0.01785714 1.         0.         1.         0.         0.93333333]
 [0.03571429 0.         1.         0.         1.         0.86666667]
 [0.64285714 1.         1.         1.         1.         0.4       ]
 ...
 [0.10714286 1.         1.         1.         1.         1.        ]
 [0.16071429 1.         0.         1.         0.         0.66666667]
 [0.375      0.         1.         1.         1.         1.        ]]


#k-NN input data test

In [ ]:
PH = input('PH: ')
Temp = input('Temperature: ')
Taste = input('Taste: ')
Odor = input('Odor: ')
Fat = input('Fat: ')
Turbidity = input('Turbidity: ')
Colour = input('Colour: ')

test_data = np.array([float(PH),int(Temp),int(Taste),int(Odor),int(Fat),int(Turbidity),int(Colour)])
print(test_data)

PH: 8.0
Temperature: 40
Taste: 1
Odor: 0
Fat: 1
Turbidity: 0
Colour: 250
[  8.  40.   1.   0.   1.   0. 250.]


#Proses k-NN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

kNN = KNeighborsClassifier(n_neighbors=3, weights='distance', metric='euclidean')
kNN.fit(train_data, train_label)
test_data = np.reshape(test_data, (1, -1))
print(test_data)
hasil = kNN.predict(test_data)
print("Hasil dari k-NN : ", hasil)


[[  8.  40.   1.   0.   1.   0. 250.]]
Hasil dari k-NN :  ['medium']
