In [ ]:
import pandas as pd
import numpy as np

## Pengambilan Data Training

In [ ]:
dataset_train = pd.read_csv('milk_training.csv')
train_data = np.array(dataset_train)[:,:-1]
print(train_data)
train_label = np.array(dataset_train)[:,-1]
print(train_label)

[[6.6 35 1 ... 1 0 254]
 [6.6 36 0 ... 0 1 253]
 [6.6 37 1 ... 1 1 255]
 ...
 [6.7 41 1 ... 0 0 247]
 [6.8 41 0 ... 0 0 255]
 [6.8 38 0 ... 0 0 255]]
['high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high

## Pengambilan Data Testing

In [ ]:
dataset_test = pd.read_csv('milk_testing.csv')
test_data = np.array(dataset_test)[:,:-1]
print(test_data)
test_label = np.array(dataset_test)[:,-1]
print(test_label)

[[6.8 45 1 ... 1 0 245]
 [6.6 37 1 ... 1 1 255]
 [6.7 38 1 ... 1 0 255]
 ...
 [6.5 37 0 ... 0 0 255]
 [6.5 40 1 ... 0 0 250]
 [6.7 45 1 ... 0 0 247]]
['high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'low' 'low' 'low' 'low'
 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low'
 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low'
 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low'
 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low'

## Naive Bayes

### Gaussian NB

In [ ]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
y_pred = gnb.fit(train_data_scaled, train_label).predict(test_data_scaled)
print(y_pred)

['high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'low' 'low' 'low' 'high'
 'high' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low'
 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low'
 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low'
 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'high' 'low' 'low' 'low' 'low'
 'medium' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low'
 'low' 'medium' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 

##### Menghitung Akurasi

In [ ]:
from sklearn.metrics import accuracy_score
akurasi = accuracy_score(test_label, bnb.predict(test_data))
print(akurasi)

0.6277602523659306


### Multinomial NB

In [ ]:
import numpy as np
rng = np.random.RandomState(1)
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()
mnb.fit(train_data, train_label)
print(mnb.predict(test_data))

['low' 'high' 'medium' 'low' 'high' 'medium' 'low' 'low' 'low' 'high'
 'medium' 'high' 'medium' 'low' 'low' 'medium' 'low' 'low' 'low' 'low'
 'high' 'medium' 'high' 'high' 'low' 'high' 'low' 'high' 'medium' 'medium'
 'low' 'high' 'low' 'low' 'medium' 'high' 'medium' 'low' 'high' 'low'
 'high' 'high' 'high' 'low' 'high' 'low' 'low' 'high' 'medium' 'high'
 'high' 'medium' 'low' 'medium' 'medium' 'low' 'low' 'low' 'high' 'medium'
 'high' 'medium' 'low' 'low' 'low' 'low' 'low' 'high' 'medium' 'high'
 'high' 'low' 'high' 'low' 'high' 'medium' 'medium' 'low' 'low' 'low'
 'low' 'low' 'low' 'low' 'medium' 'high' 'high' 'low' 'low' 'low' 'low'
 'low' 'low' 'high' 'low' 'low' 'medium' 'high' 'low' 'low' 'low' 'low'
 'low' 'low' 'low' 'high' 'low' 'low' 'medium' 'high' 'low' 'high' 'low'
 'low' 'medium' 'high' 'low' 'high' 'low' 'medium' 'high' 'low' 'high'
 'low' 'high' 'low' 'medium' 'high' 'low' 'medium' 'high' 'low' 'high'
 'low' 'low' 'high' 'low' 'low' 'medium' 'low' 'high' 'low' 'low' 'hig

### Bernoulli NB

In [ ]:
import numpy as np
from sklearn.naive_bayes import BernoulliNB
bnb = BernoulliNB()
bnb.fit(train_data, train_label)
print(bnb.predict(test_data))

['high' 'high' 'medium' 'low' 'high' 'medium' 'low' 'low' 'high' 'high'
 'medium' 'high' 'medium' 'low' 'low' 'medium' 'low' 'low' 'low' 'high'
 'high' 'medium' 'high' 'high' 'high' 'high' 'high' 'high' 'medium'
 'medium' 'low' 'high' 'low' 'high' 'medium' 'high' 'medium' 'low' 'high'
 'low' 'high' 'high' 'low' 'high' 'high' 'low' 'high' 'high' 'medium'
 'high' 'high' 'medium' 'low' 'medium' 'medium' 'low' 'low' 'high' 'high'
 'medium' 'high' 'medium' 'low' 'low' 'low' 'low' 'high' 'high' 'medium'
 'high' 'high' 'high' 'high' 'high' 'high' 'medium' 'medium' 'low' 'low'
 'low' 'medium' 'high' 'medium' 'medium' 'medium' 'high' 'low' 'low' 'low'
 'low' 'low' 'low' 'low' 'high' 'low' 'low' 'medium' 'high' 'low' 'low'
 'low' 'low' 'low' 'low' 'low' 'high' 'low' 'low' 'medium' 'high' 'low'
 'low' 'medium' 'medium' 'medium' 'high' 'low' 'high' 'low' 'medium'
 'high' 'low' 'low' 'medium' 'low' 'medium' 'medium' 'high' 'low' 'medium'
 'high' 'low' 'low' 'low' 'low' 'high' 'low' 'low' 'medium' '

## normalisasi  data dengan metode min-max

### Train Data

In [ ]:
max_element_column = np.max(train_data, 0)
min_element_column  = np.amin(train_data, 0)
newmin = 0
newmax = 1
train_data_scaled = ((train_data - min_element_column)*(newmax-newmin)/(max_element_column - min_element_column)) + newmin
print(train_data_scaled)

[[0.5538461538461538 0.017857142857142856 1.0 ... 1.0 0.0
  0.9333333333333333]
 [0.5538461538461538 0.03571428571428571 0.0 ... 0.0 1.0
  0.8666666666666667]
 [0.5538461538461538 0.05357142857142857 1.0 ... 1.0 1.0 1.0]
 ...
 [0.5692307692307692 0.125 1.0 ... 0.0 0.0 0.4666666666666667]
 [0.5846153846153845 0.125 0.0 ... 0.0 0.0 1.0]
 [0.5846153846153845 0.07142857142857142 0.0 ... 0.0 0.0 1.0]]


#### Test Data

In [ ]:
max_element_column = np.max(test_data, 0)
min_element_column  = np.amin(test_data, 0)
newmin = 0
newmax = 1
test_data_scaled = ((test_data - min_element_column)*(newmax-newmin)/(max_element_column - min_element_column)) + newmin
print(test_data_scaled)

[[0.5846153846153845 0.19642857142857142 1.0 ... 1.0 0.0
  0.3333333333333333]
 [0.5538461538461538 0.05357142857142857 1.0 ... 1.0 1.0 1.0]
 [0.5692307692307692 0.07142857142857142 1.0 ... 1.0 0.0 1.0]
 ...
 [0.5384615384615384 0.05357142857142857 0.0 ... 0.0 0.0 1.0]
 [0.5384615384615384 0.10714285714285714 1.0 ... 0.0 0.0
  0.6666666666666666]
 [0.5692307692307692 0.19642857142857142 1.0 ... 0.0 0.0
  0.4666666666666667]]
